steps:
  # First get the version tag and store it in a file
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git describe --tags --abbrev=0 > /workspace/version.txt
    id: 'Get Latest Git Tag'

  # Maven build step
  - name: 'maven:3.9.6-eclipse-temurin-21'
    args: ['mvn', 'clean', 'package', '-DskipTests']

  # Docker build step using the Git tag for versioning
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG=$(cat /workspace/version.txt)
        docker build -t us-central1-docker.pkg.dev/trusty-fuze-456211-j9/moniejoint-repo/config-server:$${VERSION_TAG} .

  # Docker push step
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG=$(cat /workspace/version.txt)
        docker push us-central1-docker.pkg.dev/trusty-fuze-456211-j9/moniejoint-repo/config-server:$${VERSION_TAG}

  # Kubernetes steps
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/config-server/namespace.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=moniejoint-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/config-server/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=moniejoint-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG=$(cat /workspace/version.txt)
        kubectl set image deployment/config-server \
          config-server=us-central1-docker.pkg.dev/trusty-fuze-456211-j9/moniejoint-repo/config-server:$${VERSION_TAG} \
          --namespace=moniejoint-ns
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=moniejoint-cluster'

images:
  - 'us-central1-docker.pkg.dev/trusty-fuze-456211-j9/moniejoint-repo/config-server:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
