apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: moniejoint-ns
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: us-central1-docker.pkg.dev/trusty-fuze-456211-j9/${PROJECT_ID}/config-server:${IMAGE_TAG}
          ports:
            - containerPort: 8001
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
